### ISSUE TITLE
Add Rails4 Support

### ISSUE THREAD

**Issue by stevebooks** [paulbaker3/raw_insert#1]
It looks like this gem is looking for protected_attributes method (which is removed in Rails4)

Here is a sample stack trace:

```
NoMethodError: undefined method `protected_attributes' for #<Class:0x007f9c9d80e170>
    /Users/stevebooks/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
    /Users/stevebooks/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/raw_insert-0b34ac037f76/lib/raw_insert.rb:25:in `define_table_structure'
    /Users/stevebooks/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/raw_insert-0b34ac037f76/lib/raw_insert.rb:6:in `raw_insert'
    /Users/stevebooks/dev/capshare/app/models/waterfall/waterfall_processor.rb:183:in `import_allocations'
    /Users/stevebooks/dev/capshare/app/models/waterfall/waterfall_processor.rb:24:in `run'
    /Users/stevebooks/dev/capshare/test/unit/models/waterfall_processor_test.rb:18:in `block in <class:WaterfallProcessorTest>'
```

**Comment by paulbaker3** [comment]
Thanks for the issue. I'll get on it.

**Comment by paulbaker3** [comment]
Fixed.
